#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xml.dom.minidom as minidom, re

# all the comments except this are autogenerated

class ParseError(Exception):
	pass

def parsePatterns(path): # Get patterns from path
	dom=minidom.parse(path) # Parse XML document
	comments=dom.getElementsByTagName("comment") # Get list of tags with name "comment"
	patterns={}
	for comment in comments:
		patterns_=comment.getElementsByTagName("pattern") # Get list of tags with name "pattern"
		for pattern in patterns_:
			try:
				text=comment.getElementsByTagName("text")[0].firstChild.nodeValue # Get list of tags with name "text"
			except IndexError:
				raise ParseError("There's a problem with comment text")
			try:
				position=comment.getElementsByTagName("position")[0].firstChild.nodeValue.strip().lower() # Get list of tags with name "position"
			except IndexError:
				position="top"
			commentStart=comment.getAttribute("commentStart") # Get "commentStart" attribute from tag
			commentEnd=comment.getAttribute("commentEnd") # Get "commentEnd" attribute from tag
			filetype=comment.getAttribute("filetype").lower() # Get "filetype" attribute from tag
			variables=comment.getElementsByTagName("variable") # Get list of tags with name "variable"
			vs={}
			for v in variables:
				index=v.getAttribute("index") # Get "index" attribute from tag
				vs[v.getAttributeNode("name").nodeValue]={"value": v.firstChild.nodeValue, "type": v.getAttribute("type"), "index": int(index) if index else 0 } # Get "index" attribute from tag
			patterns[pattern.firstChild.nodeValue]={"text": text, "position": position, "variables": vs, "filetype": filetype, "commentStart": commentStart, "commentEnd": commentEnd}
	return patterns

def comment(code, path, filetype):
	codelines=code.split("\n")
	patterns=parsePatterns(path) # Get patterns from path
	i=0
	for line in codelines:
		for pattern in patterns:
			if patterns[pattern]["filetype"]==filetype.lower():
				if re.findall(pattern, line):
					vs={}
					if patterns[pattern]["variables"]:
						for v in patterns[pattern]["variables"]:
							
							if patterns[pattern]["variables"][v]["type"]=="regex":
								res=re.findall(patterns[pattern]["variables"][v]["value"], line)
								if res:
									vs[v]=res[patterns[pattern]["variables"][v]["index"]]
								else: vs[v]=""
							else:
								vs[v]=patterns[pattern]["variables"][v]["value"]
					if not re.search(patterns[pattern]["commentStart"], line):
						if patterns[pattern]["position"]=="top":
							codelines[i]="%s\n%s" %(patterns[pattern]["commentStart"].replace("\\", "")+patterns[pattern]["text"]+patterns[pattern]["commentEnd"].replace("\\", ""), line)
						elif patterns[pattern]["position"]=="bottom":
							codelines[i]="%s\n%s" %(line, patterns[pattern]["commentStart"]+patterns[pattern]["text"]+patterns[pattern]["commetnEnd"])
						elif patterns[pattern]["position"]=="right":
							codelines[i]="%s %s" %(line, patterns[pattern]["commentStart"].replace("\\", "")+patterns[pattern]["text"]+patterns[pattern]["commentEnd"].replace("\\", ""))
						elif patterns[pattern]["position"]=="left":
							codelines[i]="%s %s" %(patterns[pattern]["text"], line)
						else:
							codelines[i]="%s\n%s" %(patterns[pattern]["text"], line)
						for v in vs:
							codelines[i]=codelines[i].replace("%%%s%%" %v, vs[v])
		i+=1
	codestr=""
	for i in codelines:
		codestr+=i+"\n"
	return codestr[0:-1]

if __name__ == "__main__":
	import argparse
	parser = argparse.ArgumentParser(description="Automatic code commenting") # Create argument parser
	parser.add_argument("file", help="File name") # Add argument to parser
	parser.add_argument("-p", "--path", help="Path to the patterns file") # Add argument to parser
	parser.add_argument("-w", "--write", action="store_true", help="Write to the file") # Add argument to parser
	parser.add_argument("-i", "--ignore-comments", action="store_true", help="Ignore comments (remove all the comments written before)") # Add argument to parser
	parser.add_argument("-cs", "--comment-start", help="Comment start") # Add argument to parser
	parser.add_argument("-ce", "--comment-end", help="Comment end") # Add argument to parser
	parser.add_argument("-f", "--filetype", help="Manually set filetype") # Add argument to parser
	args=parser.parse_args() # Parse arguments using parser options
	if args.file:
		if args.filetype:
			filetype=args.filetype
		else:
			filetype=args.file[args.file.rindex(".")+1:].lower()
		f1=open(args.file)
		code=f1.read()
		f1.close()
		if args.ignore_comments:
			comments=re.findall(args.comment_start+".*"+args.comment_end, code)
			for i in comments:
				code=code.replace(i, "")
		if args.path:
			modified=comment(code, args.path, filetype)
		else:
			modified=comment(code, "patterns.xml", filetype)
		if args.write:
			f1=open(args.file, "w")
			f1.write(modified)
			f1.close()
		else:
			print(modified)

