from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

APIPatterns = [
	url(r'^getNotes/$', 'note.functions.API_getNotes', name="getNotes"),
	url(r'^rmNote/$', 'note.functions.API_rmNote', name="rmNote"),
	url(r'^rmNotes/$', 'note.functions.API_rmNotes', name="rmNotes"),
	url(r'^register/$', 'note.functions.API_register', name="register"),
	url(r'^addNote/$', 'note.functions.API_addNote', name="addNote"),
	url(r'^addNotes/$', 'note.functions.API_addNotes', name="addNotes"),
	url(r'^deleteAccount/$', 'note.functions.API_deleteAccount', name="deleteAccount"),
]

urlpatterns = patterns('',
	
	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^(?P<pn>\d*)$', 'note.views.home'),
	url(r'^note/(?P<id>\d+)/$', 'note.views.getNote'),
	url(r'^addnote/$', 'note.views.addNote'),
	url(r'^add/$', 'note.views.addNote_page'),
	url(r'^remove/$', 'note.views.rmNote'),
	url(r'^manage/(?P<pn>\d*)$', 'note.views.manageNotes'),
	url(r'^edit/(?P<id>\d+)/$', 'note.views.edit'),
	url(r'^update/$', 'note.views.update'),
	url(r'^search/(?P<q>.*)/(?P<pn>\d+)/$', 'note.views.search'),
	url(r'^search/(?P<q>.*)/$', 'note.views.search'),
	url(r'^suggestedtags/$', 'note.views.checkSimilarityAjax'),
	url(r'^filter/(?P<pn>\d+)/$', 'note.views.filter_notes'),
	url(r'^filter/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filter_notes'),
	url(r'^filter/(?P<tags>.+)/$', 'note.views.filter_notes'),
	url(r'^filter/$', 'note.views.filter_notes'),
	url(r'^filterdone/(?P<pn>\d+)/$', 'note.views.filterDone'),
	url(r'^filterdone/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filterDone'),
	url(r'^filterdone/(?P<tags>.+)/$', 'note.views.filterDone'),
	url(r'^filterdone/$', 'note.views.filterDone'),
	url(r'^filterundone/(?P<pn>\d+)/$', 'note.views.filterUndone'),
	url(r'^filterundone/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filterUndone'),
	url(r'^filterundone/(?P<tags>.+)/$', 'note.views.filterUndone'),
	url(r'^filterundone/$', 'note.views.filterUndone'),
	url(r'^filtersnippets/(?P<pn>\d+)/$', 'note.views.filterSnippets'),
	url(r'^filtersnippets/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filterSnippets'),
	url(r'^filtersnippets/(?P<tags>.+)/$', 'note.views.filterSnippets'),
	url(r'^filtersnippets/$', 'note.views.filterSnippets'),
	url(r'^filterwarnings/(?P<pn>\d+)/$', 'note.views.filterWarnings'),
	url(r'^filterwarnings/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filterWarnings'),
	url(r'^filterwarnings/(?P<tags>.+)/$', 'note.views.filterWarnings'),
	url(r'^filterwarnings/$', 'note.views.filterWarnings'),
	url(r'^filternotes/(?P<pn>\d+)/$', 'note.views.filterNotes'),
	url(r'^filternotes/(?P<tags>.+)/(?P<pn>\d+)/$', 'note.views.filterNotes'),
	url(r'^filternotes/(?P<tags>.+)/$', 'note.views.filterNotes'),
	url(r'^filternotes/$', 'note.views.filterNotes'),
	url(r'^contact/$', 'note.views.contact'),
	url(r'^about/$', 'note.views.about'),
	url(r'^login/$', 'note.views.login_view'),
	url(r'^logout/$', 'note.views.logout_view'),
	url(r'^register/$', 'note.views.register'),
	url(r'^profile/$', 'note.views.profile'),
	url(r'^update-username/$', 'note.views.update_username'),
	url(r'^update-password/$', 'note.views.update_password'),
	url(r'^update-firstname/$', 'note.views.update_first_name'),
	url(r'^update-lastname/$', 'note.views.update_last_name'),
	url(r'^delete-account/$', 'note.views.delete_account'),
	url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'note.views.reset_password_confirm', name="password_reset_confirm"),
	url(r'^reset/$', 'note.views.reset_password', name="password_reset"),
	url(r'^reset/complete/$', 'note.views.reset_password_complete'),
	url(r'^reset/sent/$', 'note.views.reset_password_sent'),
	url(r'^api/', include(APIPatterns, namespace="API")),
)
